language: node_js
sudo: false
before_install:
  - npm install -g npm@3
script:
  - npm test
node_js:
  - "4"
  - "6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8
